/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/games/{game_date}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Games By Date
     * @description 根據指定日期獲取比賽列表，可選擇性地依隊伍名稱篩選。
     */
    get: operations['get_games_by_date_api_games__game_date__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/games/details/{game_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Game Details
     * @description 獲取單場比賽的完整細節，包含所有球員的摘要與逐打席紀錄。
     */
    get: operations['get_game_details_api_games_details__game_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/players/stats/history': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Player Stats History
     * @description 獲取指定**一個或多個**球員的球季數據歷史紀錄，支援日期篩選。
     *
     *     回傳格式為一個字典，key 為球員姓名，value 為該球員的數據歷史列表。
     */
    get: operations['get_player_stats_history_api_players_stats_history_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/analysis/games-with-players': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Games With Players
     * @description 查詢指定的所有球員同時出賽的比賽列表。
     */
    get: operations['get_games_with_players_api_analysis_games_with_players_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/analysis/players/{player_name}/last-homerun': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Last Homerun
     * @description 查詢指定球員的最後一轟，並回傳擴充後的統計數據。
     */
    get: operations['get_last_homerun_api_analysis_players__player_name__last_homerun_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/analysis/players/{player_name}/situational-at-bats': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Situational At Bats
     * @description 根據指定的壘上情境，查詢球員的打席紀錄。
     */
    get: operations['get_situational_at_bats_api_analysis_players__player_name__situational_at_bats_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/analysis/positions/{position}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Position Records
     * @description 查詢指定守備位置的所有球員出賽紀錄。
     */
    get: operations['get_position_records_api_analysis_positions__position__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/analysis/players/{player_name}/after-ibb': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Next At Bats After Ibb
     * @description 查詢指定球員被故意四壞後，下一位打者的打席結果。
     */
    get: operations['get_next_at_bats_after_ibb_api_analysis_players__player_name__after_ibb_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/analysis/streaks': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * 查詢「連線」紀錄
     * @description 查詢符合「連線」定義的打席序列。
     *     - 可依據不同的定義（連續安打、連續上壘）進行查詢。
     *     - 可指定查詢特定連續球員或特定連續棒次的連線紀錄。
     *     - 若未指定球員或棒次，則回傳所有長度達標的泛用連線。
     */
    get: operations['get_on_base_streaks_api_analysis_streaks_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/analysis/players/{player_name}/ibb-impact': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * 分析故意四壞的失分影響
     * @description 查詢指定球員被故意四壞後，該半局後續所有打席的紀錄與總失分。
     */
    get: operations['get_ibb_impact_analysis_api_analysis_players__player_name__ibb_impact_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/run_scraper': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Run Scraper Manually
     * @description 手動觸發爬蟲任務。此端點僅負責驗證輸入並分派任務至背景佇列。
     */
    post: operations['run_scraper_manually_api_run_scraper_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/update_schedule': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Update Schedule Manually
     * @description 手動觸發賽程更新任務。
     */
    post: operations['update_schedule_manually_api_update_schedule_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/system/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Health Check
     * @description 執行健康檢查，包含對資料庫與 Redis 的連線測試。
     */
    get: operations['health_check_api_system_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/system/clear-cache': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * 清除所有分析相關的 Redis 快取
     * @description 清除所有由 app.cache 模組產生的快取。
     */
    post: operations['clear_analysis_cache_api_system_clear_cache_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/system/trigger-daily-crawl': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * 觸發每日例行爬蟲任務
     * @description 此端點設計給外部排程服務 (如 GitHub Actions) 呼叫，以啟動每日爬蟲的檢查與執行流程。
     */
    post: operations['trigger_daily_crawl_task_api_system_trigger_daily_crawl_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/system/task-status/{task_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * 查詢背景任務的執行狀態
     * @description 根據任務 ID 查詢 Dramatiq 任務的狀態。
     */
    get: operations['get_task_status_api_system_task_status__task_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/dashboard/today': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Today's Dashboard
     * @description 獲取專為首頁設計的情境驅動儀表板數據。
     *
     *         - 如果今天有已完成的比賽，將回傳比賽列表。
     *         - 如果今天沒有已完成的比賽，將回傳下一場比賽的日期以及目標球隊的上一場比賽資訊。
     */
    get: operations['get_today_dashboard_api_dashboard_today_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** AtBatDetail */
    AtBatDetail: {
      /** Id */
      id: number
      /** Inning */
      inning?: number | null
      /** Sequence In Game */
      sequence_in_game?: number | null
      /** Result Short */
      result_short?: string | null
      /** Result Description Full */
      result_description_full?: string | null
      /** Opposing Pitcher Name */
      opposing_pitcher_name?: string | null
      /** Pitch Sequence Details */
      pitch_sequence_details?: string | null
      /** Runners On Base Before */
      runners_on_base_before?: string | null
      /** Outs Before */
      outs_before?: number | null
      /** Runs Scored On Play */
      runs_scored_on_play: number
      result_type?: components['schemas']['AtBatResultType'] | null
    }
    /**
     * AtBatDetailForStreak
     * @description 為「連線」功能擴充的打席模型，額外包含打者姓名與棒次資訊。
     */
    AtBatDetailForStreak: {
      /** Id */
      id: number
      /** Inning */
      inning?: number | null
      /** Sequence In Game */
      sequence_in_game?: number | null
      /** Result Short */
      result_short?: string | null
      /** Result Description Full */
      result_description_full?: string | null
      /** Opposing Pitcher Name */
      opposing_pitcher_name?: string | null
      /** Pitch Sequence Details */
      pitch_sequence_details?: string | null
      /** Runners On Base Before */
      runners_on_base_before?: string | null
      /** Outs Before */
      outs_before?: number | null
      /** Runs Scored On Play */
      runs_scored_on_play: number
      result_type?: components['schemas']['AtBatResultType'] | null
      /**
       * Player Name
       * @description 打者姓名
       */
      player_name: string
      /**
       * Batting Order
       * @description 棒次
       */
      batting_order?: string | null
    }
    /**
     * AtBatResultType
     * @enum {string}
     */
    AtBatResultType:
      | 'UNSPECIFIED'
      | 'ON_BASE'
      | 'OUT'
      | 'SACRIFICE'
      | 'FIELDERS_CHOICE'
      | 'ERROR'
      | 'incomplete_pa'
    /** DashboardHasGamesResponse */
    DashboardHasGamesResponse: {
      /**
       * Status
       * @constant
       */
      status: 'HAS_TODAY_GAMES'
      /** Games */
      games: components['schemas']['GameResultWithDetails'][]
    }
    /** DashboardNoGamesResponse */
    DashboardNoGamesResponse: {
      /**
       * Status
       * @constant
       */
      status: 'NO_TODAY_GAMES'
      /**
       * Next Game Date
       * @description 下一場比賽的日期
       * @example 2025-08-17
       */
      next_game_date?: string | null
      /** @description 目標球隊的上一場完整比賽數據 */
      last_target_team_game?: components['schemas']['GameResultWithDetails'] | null
    }
    /** GameResult */
    GameResult: {
      /** Id */
      id: number
      /** Cpbl Game Id */
      cpbl_game_id?: string | null
      /**
       * Game Date
       * Format: date
       */
      game_date: string
      /** Game Time */
      game_time?: string | null
      /** Home Team */
      home_team: string
      /** Away Team */
      away_team: string
      /** Home Score */
      home_score?: number | null
      /** Away Score */
      away_score?: number | null
      /** Venue */
      venue?: string | null
      /** Status */
      status?: string | null
    }
    /** GameResultWithDetails */
    GameResultWithDetails: {
      /** Id */
      id: number
      /** Cpbl Game Id */
      cpbl_game_id?: string | null
      /**
       * Game Date
       * Format: date
       */
      game_date: string
      /** Game Time */
      game_time?: string | null
      /** Home Team */
      home_team: string
      /** Away Team */
      away_team: string
      /** Home Score */
      home_score?: number | null
      /** Away Score */
      away_score?: number | null
      /** Venue */
      venue?: string | null
      /** Status */
      status?: string | null
      /**
       * Player Summaries
       * @default []
       */
      player_summaries: components['schemas']['PlayerGameSummary'][]
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /**
     * IbbImpactResult
     * @description 代表一次故意四壞事件及其後續影響的模型。
     */
    IbbImpactResult: {
      /**
       * Game Id
       * @description 比賽的唯一 ID
       */
      game_id: number
      /**
       * Game Date
       * Format: date
       * @description 比賽日期
       */
      game_date: string
      /**
       * Inning
       * @description 事件發生的局數
       */
      inning: number
      /**
       * Opponent Team
       * @description 對戰球隊
       */
      opponent_team: string
      /** @description 故意四壞的打席紀錄 */
      intentional_walk: components['schemas']['AtBatDetailForStreak']
      /**
       * Subsequent At Bats
       * @description 該半局後續的所有打席
       */
      subsequent_at_bats: components['schemas']['AtBatDetailForStreak'][]
      /**
       * Runs Scored After Ibb
       * @description 在 IBB 之後，該半局得到的總分數
       */
      runs_scored_after_ibb: number
    }
    /** LastHomerunStats */
    LastHomerunStats: {
      last_homerun: components['schemas']['AtBatDetail']
      /**
       * Game Date
       * Format: date
       */
      game_date: string
      /** Days Since */
      days_since: number
      /** Games Since */
      games_since: number
      /** At Bats Since */
      at_bats_since: number
      /** @description 球員生涯數據 */
      career_stats?: components['schemas']['PlayerCareerStats'] | null
    }
    /** NextAtBatResult */
    NextAtBatResult: {
      intentional_walk: components['schemas']['AtBatDetail']
      next_at_bat?: components['schemas']['AtBatDetail'] | null
    }
    /**
     * OnBaseStreak
     * @description 代表一次完整「連線」事件的模型。
     */
    OnBaseStreak: {
      /**
       * Game Id
       * @description 比賽的唯一 ID
       */
      game_id: number
      /**
       * Game Date
       * Format: date
       * @description 比賽日期
       */
      game_date: string
      /**
       * Inning
       * @description 事件發生的局數
       */
      inning: number
      /**
       * Streak Length
       * @description 此次連線的人次長度
       */
      streak_length: number
      /**
       * Opponent Team
       * @description 對戰球隊
       */
      opponent_team: string
      /**
       * Runs Scored During Streak
       * @description 在這次連線期間得到的總分數
       */
      runs_scored_during_streak: number
      /**
       * At Bats
       * @description 組成此次連線的所有打席詳細紀錄
       */
      at_bats: components['schemas']['AtBatDetailForStreak'][]
    }
    /** PlayerCareerStats */
    PlayerCareerStats: {
      /** Player Name */
      player_name: string
      /** Debut Date */
      debut_date?: string | null
      /** Handedness */
      handedness?: string | null
      /** Games Played */
      games_played: number
      /** Plate Appearances */
      plate_appearances: number
      /** At Bats */
      at_bats: number
      /** Runs Scored */
      runs_scored: number
      /** Hits */
      hits: number
      /** Singles */
      singles: number
      /** Doubles */
      doubles: number
      /** Triples */
      triples: number
      /** Homeruns */
      homeruns: number
      /** Rbi */
      rbi: number
      /** Total Bases */
      total_bases: number
      /** Strikeouts */
      strikeouts: number
      /** Walks */
      walks: number
      /** Intentional Walks */
      intentional_walks: number
      /** Hit By Pitch */
      hit_by_pitch: number
      /** Stolen Bases */
      stolen_bases: number
      /** Caught Stealing */
      caught_stealing: number
      /** Sacrifice Hits */
      sacrifice_hits: number
      /** Sacrifice Flies */
      sacrifice_flies: number
      /** Gidp */
      gidp: number
      /** Ground Outs */
      ground_outs: number
      /** Fly Outs */
      fly_outs: number
      /** Avg */
      avg?: number | null
      /** Obp */
      obp?: number | null
      /** Slg */
      slg?: number | null
      /** Ops */
      ops?: number | null
      /** Go Ao Ratio */
      go_ao_ratio?: number | null
      /** Sb Percentage */
      sb_percentage?: number | null
      /** Ops Plus */
      ops_plus?: number | null
      /** K Percentage */
      k_percentage?: number | null
      /** Bb Percentage */
      bb_percentage?: number | null
      /** Bb Per K */
      bb_per_k?: number | null
      /** Babip */
      babip?: number | null
      /** Bip Percentage */
      bip_percentage?: number | null
      /** Id */
      id: number
      /** Updated At */
      updated_at?: string | null
    }
    /** PlayerGameSummary */
    PlayerGameSummary: {
      /** Id */
      id: number
      /** Game Id */
      game_id: number
      /** Player Name */
      player_name: string
      /** Team Name */
      team_name?: string | null
      /** Batting Order */
      batting_order?: string | null
      /** Position */
      position?: string | null
      /** Plate Appearances */
      plate_appearances: number
      /** At Bats */
      at_bats: number
      /** Runs Scored */
      runs_scored: number
      /** Hits */
      hits: number
      /** Doubles */
      doubles: number
      /** Triples */
      triples: number
      /** Homeruns */
      homeruns: number
      /** Rbi */
      rbi: number
      /** Walks */
      walks: number
      /** Intentional Walks */
      intentional_walks: number
      /** Hit By Pitch */
      hit_by_pitch: number
      /** Strikeouts */
      strikeouts: number
      /** Stolen Bases */
      stolen_bases: number
      /** Caught Stealing */
      caught_stealing: number
      /** Sacrifice Hits */
      sacrifice_hits: number
      /** Sacrifice Flies */
      sacrifice_flies: number
      /** Gidp */
      gidp: number
      /** Errors */
      errors: number
      /** Avg Cumulative */
      avg_cumulative?: number | null
      /** At Bat Results Summary */
      at_bat_results_summary?: string | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /**
       * At Bat Details
       * @default []
       */
      at_bat_details: components['schemas']['AtBatDetail'][]
    }
    /** PlayerSeasonStatsHistory */
    PlayerSeasonStatsHistory: {
      /** Player Name */
      player_name: string
      /** Team Name */
      team_name?: string | null
      /** Data Retrieved Date */
      data_retrieved_date?: string | null
      /** Games Played */
      games_played: number
      /** Plate Appearances */
      plate_appearances: number
      /** At Bats */
      at_bats: number
      /** Runs Scored */
      runs_scored: number
      /** Hits */
      hits: number
      /** Rbi */
      rbi: number
      /** Homeruns */
      homeruns: number
      /** Singles */
      singles: number
      /** Doubles */
      doubles: number
      /** Triples */
      triples: number
      /** Total Bases */
      total_bases: number
      /** Strikeouts */
      strikeouts: number
      /** Stolen Bases */
      stolen_bases: number
      /** Gidp */
      gidp: number
      /** Sacrifice Hits */
      sacrifice_hits: number
      /** Sacrifice Flies */
      sacrifice_flies: number
      /** Walks */
      walks: number
      /** Intentional Walks */
      intentional_walks: number
      /** Hit By Pitch */
      hit_by_pitch: number
      /** Caught Stealing */
      caught_stealing: number
      /** Ground Outs */
      ground_outs: number
      /** Fly Outs */
      fly_outs: number
      /** Avg */
      avg?: number | null
      /** Obp */
      obp?: number | null
      /** Slg */
      slg?: number | null
      /** Ops */
      ops?: number | null
      /** Go Ao Ratio */
      go_ao_ratio?: number | null
      /** Sb Percentage */
      sb_percentage?: number | null
      /** Silver Slugger Index */
      silver_slugger_index?: number | null
      /** Id */
      id: number
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
    }
    /**
     * RunnersSituation
     * @enum {string}
     */
    RunnersSituation: 'bases_empty' | 'scoring_position' | 'bases_loaded'
    /** ScraperRequest */
    ScraperRequest: {
      /** Mode */
      mode: string
      /** Date */
      date?: string | null
    }
    /**
     * SituationalAtBatDetail
     * @description 擴充 AtBatDetail，增加比賽日期與對戰對手資訊。
     */
    SituationalAtBatDetail: {
      /** Id */
      id: number
      /** Inning */
      inning?: number | null
      /** Sequence In Game */
      sequence_in_game?: number | null
      /** Result Short */
      result_short?: string | null
      /** Result Description Full */
      result_description_full?: string | null
      /** Opposing Pitcher Name */
      opposing_pitcher_name?: string | null
      /** Pitch Sequence Details */
      pitch_sequence_details?: string | null
      /** Runners On Base Before */
      runners_on_base_before?: string | null
      /** Outs Before */
      outs_before?: number | null
      /** Runs Scored On Play */
      runs_scored_on_play: number
      result_type?: components['schemas']['AtBatResultType'] | null
      /**
       * Game Date
       * Format: date
       * @description 比賽日期
       */
      game_date: string
      /**
       * Opponent Team
       * @description 對戰球隊
       */
      opponent_team: string
    }
    /**
     * StreakDefinition
     * @enum {string}
     */
    StreakDefinition: 'consecutive_hits' | 'consecutive_on_base' | 'consecutive_advancements'
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  get_games_by_date_api_games__game_date__get: {
    parameters: {
      query?: {
        /** @description 依特定隊伍名稱篩選比賽 */
        team_name?: string | null
      }
      header?: never
      path: {
        game_date: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GameResult'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_game_details_api_games_details__game_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        game_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GameResultWithDetails']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_player_stats_history_api_players_stats_history_get: {
    parameters: {
      query: {
        /** @description 要查詢的一個或多個球員姓名 */
        player_name: string[]
        start_date?: string | null
        end_date?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: components['schemas']['PlayerSeasonStatsHistory'][]
          }
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_games_with_players_api_analysis_games_with_players_get: {
    parameters: {
      query: {
        /** @description 球員姓名列表 */
        players: string[]
        /** @description 要跳過的紀錄數量 */
        skip?: number
        /** @description 每頁回傳的最大紀錄數量 */
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GameResultWithDetails'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_last_homerun_api_analysis_players__player_name__last_homerun_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        player_name: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LastHomerunStats']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_situational_at_bats_api_analysis_players__player_name__situational_at_bats_get: {
    parameters: {
      query: {
        situation: components['schemas']['RunnersSituation']
        /** @description 要跳過的紀錄數量 */
        skip?: number
        /** @description 每頁回傳的最大紀錄數量 */
        limit?: number
      }
      header?: never
      path: {
        player_name: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SituationalAtBatDetail'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_position_records_api_analysis_positions__position__get: {
    parameters: {
      query?: {
        /** @description 要跳過的紀錄數量 */
        skip?: number
        /** @description 每頁回傳的最大紀錄數量 */
        limit?: number
      }
      header?: never
      path: {
        position: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PlayerGameSummary'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_next_at_bats_after_ibb_api_analysis_players__player_name__after_ibb_get: {
    parameters: {
      query?: {
        /** @description 要跳過的紀錄數量 */
        skip?: number
        /** @description 每頁回傳的最大紀錄數量 */
        limit?: number
      }
      header?: never
      path: {
        player_name: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['NextAtBatResult'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_on_base_streaks_api_analysis_streaks_get: {
    parameters: {
      query?: {
        /** @description 要使用的連線定義 */
        definition_name?: components['schemas']['StreakDefinition']
        /** @description 連線的最短長度 */
        min_length?: number
        /** @description 要查詢的連續球員姓名列表 */
        player_names?: string[] | null
        /** @description 要查詢的連續棒次列表 */
        lineup_positions?: number[] | null
        /** @description 要跳過的紀錄數量 */
        skip?: number
        /** @description 每頁回傳的最大紀錄數量 */
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['OnBaseStreak'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_ibb_impact_analysis_api_analysis_players__player_name__ibb_impact_get: {
    parameters: {
      query?: {
        /** @description 要跳過的紀錄數量 */
        skip?: number
        /** @description 每頁回傳的最大紀錄數量 */
        limit?: number
      }
      header?: never
      path: {
        player_name: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IbbImpactResult'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  run_scraper_manually_api_run_scraper_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ScraperRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_schedule_manually_api_update_schedule_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
  health_check_api_system_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  clear_analysis_cache_api_system_clear_cache_post: {
    parameters: {
      query?: never
      header: {
        'x-api-key': string
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  trigger_daily_crawl_task_api_system_trigger_daily_crawl_post: {
    parameters: {
      query?: never
      header: {
        'x-api-key': string
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_task_status_api_system_task_status__task_id__get: {
    parameters: {
      query?: never
      header: {
        'x-api-key': string
      }
      path: {
        task_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_today_dashboard_api_dashboard_today_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json':
            | components['schemas']['DashboardHasGamesResponse']
            | components['schemas']['DashboardNoGamesResponse']
        }
      }
    }
  }
}
