// app/layout.tsx
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import QueryProvider from '@/components/providers/QueryProvider' // <-- 匯入 Provider
import { Navbar } from '@/components/ui/Navbar'
import { Footer } from '@/components/ui/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'CPBL 數據視覺化應用程式',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <Navbar />
        </header>
        <QueryProvider>
          {/* <-- 在此處包裹 children */}
          {children}
        </QueryProvider>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  )
}
