// app/layout.tsx
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import QueryProvider from '@/components/providers/QueryProvider'
import { SpeedInsights } from '@vercel/speed-insights/next' // 1. 匯入 SpeedInsights
import { Navbar } from '@/components/ui/Navbar'
import { Footer } from '@/components/ui/Footer'
import { ThemeProvider } from '@/components/providers/ThemeProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'CPBL 數據視覺化應用程式',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <header>
            <Navbar />
          </header>
          <QueryProvider>{children}</QueryProvider>
          <footer>
            <Footer />
          </footer>
        </ThemeProvider>
        <SpeedInsights />
      </body>
    </html>
  )
}
